version: '3'
services:
  spigot:
    build: ./spigot-server
    container_name: spigot
    ports:
      - "25565:25565"
      - "25575:25575"
      - "8123:8123"
    volumes:
      - ./volumes/minecraft:/minecraft
    environment:
      - REV=1.14.4
      - FORCE_REBUILD=false # DELETES MINECRAFT VOLUME AND REBUILDS spigot.jar
      - EULA=true
    restart: always
  web-rcon:
    build: ./web-rcon
    container_name: web-rcon
    ports:
      - "8080:3000"
    environment:
      - WEB_PASSWORD=12345
      - RCON_HOST=spigot
    restart: always
