version: '3'
services:
  spigot:
    build: ./spigot-server
    ports:
      - "25565:25565"
    volumes:
      - ./volumes/minecraft:/minecraft
    environment:
      - REV=1.14.4
      - FORCE_REBUILD=false # DELETES MINECRAFT VOLUME AND REBUILDS spigot.jar